### ISSUE TITLE
TODO hexscatter-bean

### ISSUE THREAD

**Issue by erikhuizinga** [erikhuizinga/honeycomb#1]
- [ ] Restyle code
- [ ] Fix and update documentation
- [ ] Fix and update code
  - [ ] Fix bug: oval grids around hex vertices should align, but do not
  - [ ] Fix bug: resolution of 2 may throw an error
    - Determine other erroneous resolutions e.g. low resolutions of 3, 4, 5?
    - Caused by even resolution?
  - [ ] Fix bug: `drawEdges` may not work and issues a warning
    - Related to [this section](https://mathworks.com/help/matlab/ref/patch-properties.html#property_d0e725867) in MATLAB's documentation
  - [ ] Use current MATLAB functions and constructs while retaining compatibility
